export const  ADD_ADDRESS = 'ADD_ADDRESS'
export const REMOVE_ADDRESS= 'REMOVE_ADDRESS'
export const EDIT_ADDRESS= 'EDIT_ADDRESS'

export const ADDRESS_SUCCESS = 'ADDRESS_SUCCESS'
export const ADDRESS_REQUEST = 'ADDRESS_REQUEST'
export const ADDRESS_FAIL = 'ADDRESS_FALI'
export const ADDRESS_DELETE = 'ADDRESS_DELETE'