export const  REVIEW_DATA_REQUEST = "REVIEW_DATA_REQUEST"
export const  REVIEW_DATA_SUCCESS = "REVIEW_DATA_SUCCESS"
export const  REVIEW_DATA_FAILS = "REVIEW_DATA_FAILS"

export const  REVIEW_SAVEDATA_REQEST = "REVIEW_SAVEDATA_REQEST"
export const  REVIEW_SAVEDATA_SUCCESS = "REVIEW_SAVEDATA_SUCCESS"
export const  REVIEW_SAVEDATA_FAILS = "REVIEW_SAVEDATA_FAILS"