export const  ORDER_LIST_REQUEST = 'ORDER_LIST_REQUEST'
export const  ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS'
export const  ORDER_LIST_FAIL = 'ORDER_LIST_FAIL'

export const OWNER_ACTIVE_ORDER_REQUEST = "ACTIVE_ORDER"
export const OWNER_ACTIVE_ORDER_SUCCESS = "ACTIVE_ORDER_SUCCESS"
export const OWNER_ACTIVE_ORDER_FAIL = "ACTIVE_ORDER_FAIL"


export const USER_ACTIVE_ORDER_REQUEST = "ACTIVE_ORDER"
export const USER_ACTIVE_ORDER_SUCCESS = "ACTIVE_ORDER_SUCCESS"
export const USER_ACTIVE_ORDER_FAIL = "ACTIVE_ORDER_FAIL"


export const STATUS_UPDATE_SUCCESS = "STATUS_UPDATE_SUCCESS"
export const STATUS_UPDATE_REQUEST = "STATUS_UPDATE_REQUEST"
export const STATUS_UPDATE_FAIL = "STATUS_UPDATE_REQUEST"