export const  REVIEW_USERDATA_REQUEST = "REVIEW_USERDATA_REQUEST"
export const  REVIEW_USERDATA_SUCCESS = "REVIEW_USERDATA_SUCCESS"
export const  REVIEW_USERDATA_FAILS = "REVIEW_USERDATA_FAILS"

export const  REVIEW_OWNERDATA_REQUEST = "REVIEW_OWNERDATA_REQUEST"
export const  REVIEW_OWNERDATA_SUCCESS = "REVIEW_OWNERDATA_SUCCESS"
export const  REVIEW_OWNERDATA_FAILS = "REVIEW_OWNERDATA_FAILS"

export const  REVIEW_SAVEDATA_REQEST = "REVIEW_SAVEDATA_REQEST"
export const  REVIEW_SAVEDATA_SUCCESS = "REVIEW_SAVEDATA_SUCCESS"
export const  REVIEW_SAVEDATA_FAILS = "REVIEW_SAVEDATA_FAILS"